webgriffe_admin_notification_subscription:
    resource: |
        alias: webgriffe.back_in_stock_notification_subscription
        section: admin
        path: subscriptions
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: webgriffe_admin_notification_subscription
        vars:
            all:
                hook_prefix: 'webgriffe_sylius_back_in_stock_notification_plugin.admin.notification_subscription'
    type: sylius.resource
