sylius_resource:
    resources:
        webgriffe.back_in_stock_notification_subscription:
            driver: doctrine/orm
            classes:
                model: Webgriffe\SyliusBackInStockNotificationPlugin\Entity\Subscription
