sylius_grid:
  templates:
    action:
      customer_details: "@WebgriffeSyliusBackInStockNotificationPlugin/Admin/customerDetails.html.twig"

  grids:
    webgriffe_admin_notification_subscription:
      driver:
        name: doctrine/orm
        options:
          class: Webgriffe\SyliusBackInStockNotificationPlugin\Entity\Subscription
      fields:
        image:
          type: twig
          label: sylius.ui.image
          path: productVariant.product
          options:
            template: "@SyliusAdmin/Product/Grid/Field/image.html.twig"
        product_variant_code:
          type: string
          label: sylius.ui.code
          sortable: ~
          path: productVariant.code
        name:
          type: string
          label: sylius.ui.name
          sortable: translation.name
          path: productVariant.product.name
        email:
          type: string
          label: sylius.ui.email
        created_at:
          type: datetime
          label: sylius.ui.date
          sortable: createdAt
          options:
            format: d-m-Y H:i:s
        notify:
          type: twig
          label: sylius.ui.state
          options:
            template: "@WebgriffeSyliusBackInStockNotificationPlugin/Admin/Grid/Field/notify.html.twig"
      filters:
        email:
          type: string
          label: sylius.ui.email
        code:
          type: string
          label: sylius.ui.code
          options:
            fields: [productVariant.code]
        created_at:
          type: date
          label: sylius.ui.date
        notify:
          type: boolean
          label: sylius.ui.state
      actions:
        item:
          product_details:
            label: webgriffe_bisn.admin.show_product
            type: show
            options:
              link:
                route: sylius_admin_product_show
                parameters:
                  id: resource.productVariant.product.id
          customer_details:
            label: webgriffe_bisn.admin.show_customer
            type: customer_details
            options:
              link:
                route: sylius_admin_customer_show
                data:
                  customer: resource.customer
          delete:
            label: webgriffe_bisn.admin.delete_supscription
            type: delete

    webgriffe_back_in_stock_notification_account_list_subscriptions:
      driver:
        name: doctrine/orm
        options:
          class: Webgriffe\SyliusBackInStockNotificationPlugin\Entity\Subscription
          repository:
            method: createByCustomerIdAndChannelIdQueryBuilder
            arguments:
              - "expr:service('sylius.context.customer').getCustomer().getId()"
              - "expr:service('sylius.context.channel').getChannel().getId()"
      fields:
        product:
          type: twig
          label: sylius.ui.product
          path: productVariant
          options:
            template: "@WebgriffeSyliusBackInStockNotificationPlugin/MyAccount/productCell.html.twig"
        product_variant_code:
          type: string
          label: sylius.ui.code
          path: productVariant.code
        notify:
          type: twig
          label: sylius.ui.state
          options:
            template: "@WebgriffeSyliusBackInStockNotificationPlugin/MyAccount/notify.html.twig"
        created_at:
          type: datetime
          label: sylius.ui.date
          options:
            format: d-m-Y H:i:s
        delete:
          type: twig
          path: hash
          label: sylius.ui.action
          options:
            template: "@WebgriffeSyliusBackInStockNotificationPlugin/MyAccount/deleteCell.html.twig"
